### ISSUE TITLE
Really old versions of docs are showing up first

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image-web#68] opened 2019-10-21 18:22 UTC
![image](https://user-images.githubusercontent.com/90008/67231885-2e98dc00-f40e-11e9-80d4-804d3c6b5dfc.png)

**Comment by jni** [comment] 2019-10-22 00:08
Looking at [robots.txt](https://github.com/scikit-image/scikit-image-web/blob/master/robots.txt), this looks like a bug in duckduckgo rather than skimage? (The word "homography" appears in the "ProjectiveTransform" docstring on stable.)

Having said that, it's so awesome that I can make the same search and get the same results, unlike with Google.

**Comment by hmaarrfk** [comment] 2019-10-22 00:32
I got it with Google first. I just don't like screenshoting them

**Comment by jni** [comment] 2019-10-22 00:36
Hmm. Well, I don't know, from the URL of the results and the formatting of the robots file, things should be working as expected. @stefanv any ideas?

**Comment by hmaarrfk** [comment] 2019-10-22 00:51
![Screenshot_20191021-205106](https://user-images.githubusercontent.com/90008/67253212-8e11de80-f444-11e9-9389-1fdbc302fd22.png)

**Comment by jni** [comment] 2019-10-22 00:55
@hmaarrfk don't worry, I believed you the first time! =)

**Comment by hmaarrfk** [comment] 2019-10-22 01:00
Ah ok. I thought you couldn't reproduce

**Comment by alexdesiqueira** [comment] 2019-11-02 17:07
I can reproduce it @ Google:
![Screenshot from 2019-11-02 10-06-55](https://user-images.githubusercontent.com/5776022/68074477-91686c80-fd58-11e9-896b-6d5d0c91eac1.png)

**Comment by stefanv** [comment] 2019-11-02 17:38
Could be because we recently fixed some links in old documentation.

**Comment by sciunto** [comment] 2020-07-29 05:22
Seems to be fixed now.

I just discovered a link from @tonysyu http://tonysyu.github.io/scikit-image/api/skimage.transform.html in the list. @tonysyu Would you like to keep this online?

**Comment by mkcor** [comment] 2020-09-29 17:15
Yes, it's kind of better now (same top 3 with `homography scikit-image`) ;)

![google_search_version](https://user-images.githubusercontent.com/2227806/94590894-b6769f80-0287-11eb-807e-53b783596b18.png)

**Comment by rfezzani** [comment] 2020-10-02 15:15
It seems fixed:
![Capture d’écran de 2020-10-02 17-13-05](https://user-images.githubusercontent.com/3438227/94939633-b3bbba80-04d2-11eb-8627-0a648089376d.png)
:tada: :tada: :tada:

**Closed by rfezzani** 2020-10-02 15:15 UTC
